# Generated by Django 5.2.6 on 2025-10-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytemplate',
            name='chat_history',
            field=models.JSONField(default=list, help_text='Condensed chat history about this strategy'),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='is_system_template',
            field=models.BooleanField(default=False, help_text='True for pre-built templates, False for user/chat-created templates'),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='latest_parameters',
            field=models.JSONField(default=dict, help_text='Most recent strategy parameters'),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='latest_strategy_code',
            field=models.TextField(blank=True, help_text='Most recent version of the strategy code (auto-updated)'),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='linked_strategy',
            field=models.ForeignKey(blank=True, help_text='Strategy this template is linked to (for chat-based templates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_template', to='strategy_api.strategy'),
        ),
    ]
