# Generated by Django 5.2.6 on 2025-10-28 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0002_strategytemplate_chat_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-set session title', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is this session still active?')),
                ('context_summary', models.TextField(blank=True, help_text='AI-generated summary of the conversation')),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages in this session')),
                ('model_name', models.CharField(default='gemini-1.5-flash', help_text='AI model used', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature setting for AI responses')),
                ('max_tokens', models.IntegerField(default=2048, help_text='Max tokens for AI responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of last message', null=True)),
                ('strategy', models.ForeignKey(blank=True, help_text='Associated strategy for this chat session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_chat_sessions', to='strategy_api.strategy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Message sender role', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens in this message', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (strategy references, validation results, etc.)')),
                ('function_call', models.JSONField(blank=True, help_text='Function call data if assistant performed an action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='strategy_api.strategychat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strategychat',
            index=models.Index(fields=['session_id'], name='strategy_ap_session_5dd70b_idx'),
        ),
        migrations.AddIndex(
            model_name='strategychat',
            index=models.Index(fields=['user', '-updated_at'], name='strategy_ap_user_id_30be71_idx'),
        ),
        migrations.AddIndex(
            model_name='strategychatmessage',
            index=models.Index(fields=['session', 'created_at'], name='strategy_ap_session_abac27_idx'),
        ),
    ]
