# Generated by Django 5.2.7 on 2025-12-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0002_bot_performance'),
        ('strategy_api', '0004_alter_strategychat_model_name'),
    ]

    operations = [
    ]
