# Generated by Django 5.0.1 on 2026-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0006_add_latest_backtest_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='GitHub OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='GitHub OAuth refresh token')),
                ('expires_at', models.DateTimeField(help_text='Token expiration datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed', models.DateTimeField(blank=True, help_text='Last token refresh time', null=True)),
                ('github_user', models.CharField(blank=True, help_text='Authenticated GitHub username', max_length=200)),
                ('client_id', models.CharField(blank=True, help_text='OAuth client ID used', max_length=200)),
            ],
            options={
                'verbose_name': 'Copilot Authentication',
                'verbose_name_plural': 'Copilot Authentications',
            },
        ),
    ]
