# Generated by Django 5.0.1 on 2026-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0007_add_copilot_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copilotauth',
            name='refresh_token',
            field=models.TextField(blank=True, default='', help_text='GitHub OAuth refresh token', null=True),
        ),
    ]
