# Generated by Django 5.0.1 on 2026-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_api", "0008_fix_copilot_refresh_token_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestbacktestresult",
            name="symbol_stats",
            field=models.JSONField(
                default=list,
                help_text="Per-symbol trade stats: [{symbol, trades, win_rate, net_profit, return_pct}]",
            ),
        ),
    ]
