"""
Cleanup Generated Files Script

This script removes all files generated by the agent during user interactions:
- Generated strategy code (Python files and JSON schemas)
- Backtest records (signals, patterns, results)
- Chronicle files for strategies

PRESERVES:
- Learning patterns database (error_learning.db)
- Knowledge bases
- Template files
- Documentation
"""

import os
import shutil
from pathlib import Path
from datetime import datetime

# Root directory
ROOT = Path(__file__).parent

# Directories to clean
CLEANUP_TARGETS = {
    'generated_strategies': ROOT / 'Backtest' / 'codes',
    'backtest_signals': ROOT / 'Backtest' / 'signals',
    'backtest_results': ROOT / 'Backtest' / 'results',
    'generated_codes': ROOT / 'codes' / 'codes',
}

# Patterns to exclude (KEEP these files)
EXCLUDE_PATTERNS = [
    'README.md',
    'CODES_README.md',
    '__pycache__',
    '.git',
    'error_learning.db',  # Learning database
    'template',           # Template files
    'example_strategy.py',
    'example_gemini_strategy.py',
    'STRATEGY_TEMPLATE.md',
    'strategy_template_enhanced.py',
]

# Directories to fully clean (remove all contents)
FULL_CLEAN_DIRS = [
    ROOT / 'Backtest' / 'signals',
    ROOT / 'Backtest' / 'results',
]


def should_keep_file(file_path: Path) -> bool:
    """Check if a file should be kept based on exclude patterns."""
    file_name = file_path.name
    
    # Keep files matching exclude patterns
    for pattern in EXCLUDE_PATTERNS:
        if pattern in str(file_path):
            return True
    
    return False


def clean_directory(directory: Path, full_clean: bool = False):
    """Clean a directory of generated files."""
    if not directory.exists():
        print(f"⚠️  Directory doesn't exist: {directory}")
        return
    
    print(f"\n🧹 Cleaning: {directory}")
    
    files_removed = 0
    files_kept = 0
    
    if full_clean:
        # Remove everything except README files
        for item in directory.iterdir():
            if item.name == 'README.md':
                files_kept += 1
                continue
            
            if item.is_file():
                item.unlink()
                files_removed += 1
                print(f"  ✓ Removed: {item.name}")
            elif item.is_dir() and item.name != '__pycache__':
                shutil.rmtree(item)
                files_removed += 1
                print(f"  ✓ Removed dir: {item.name}")
    else:
        # Selective removal
        for item in directory.rglob('*'):
            if not item.is_file():
                continue
            
            if should_keep_file(item):
                files_kept += 1
                continue
            
            # Remove generated files
            try:
                item.unlink()
                files_removed += 1
                print(f"  ✓ Removed: {item.relative_to(directory)}")
            except Exception as e:
                print(f"  ❌ Error removing {item.name}: {e}")
    
    print(f"  📊 Removed: {files_removed} | Kept: {files_kept}")


def clean_strategy_codes():
    """Clean generated strategy Python and JSON files."""
    codes_dir = ROOT / 'Backtest' / 'codes'
    
    if not codes_dir.exists():
        print(f"⚠️  Codes directory doesn't exist: {codes_dir}")
        return
    
    print(f"\n🧹 Cleaning strategy codes: {codes_dir}")
    
    files_removed = 0
    
    for item in codes_dir.iterdir():
        if not item.is_file():
            continue
        
        # Keep specific files
        if should_keep_file(item):
            continue
        
        # Remove .py and .json files (generated strategies)
        if item.suffix in ['.py', '.json', '.html']:
            try:
                item.unlink()
                files_removed += 1
                print(f"  ✓ Removed: {item.name}")
            except Exception as e:
                print(f"  ❌ Error removing {item.name}: {e}")
    
    # Clean subdirectories
    for subdir in ['results', 'trades', 'temp', 'generated_by_keys_flash']:
        subdir_path = codes_dir / subdir
        if subdir_path.exists() and subdir_path.is_dir():
            try:
                shutil.rmtree(subdir_path)
                files_removed += 1
                print(f"  ✓ Removed directory: {subdir}")
            except Exception as e:
                print(f"  ❌ Error removing {subdir}: {e}")
    
    print(f"  📊 Total removed: {files_removed}")


def main():
    """Main cleanup function."""
    print("=" * 60)
    print("🧹 CLEANUP GENERATED FILES")
    print("=" * 60)
    print(f"📅 Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Clean strategy codes (Python and JSON files)
    clean_strategy_codes()
    
    # Clean backtest signals (full clean - remove all chronicle files)
    clean_directory(ROOT / 'Backtest' / 'signals', full_clean=True)
    
    # Clean backtest results (full clean)
    clean_directory(ROOT / 'Backtest' / 'results', full_clean=True)
    
    # Clean generated_strategies folder
    generated_strategies = ROOT / 'Backtest' / 'generated_strategies'
    if generated_strategies.exists():
        clean_directory(generated_strategies, full_clean=False)
    
    print("\n" + "=" * 60)
    print("✅ CLEANUP COMPLETE!")
    print("=" * 60)
    print("\n📋 What was cleaned:")
    print("  • Generated strategy Python files (.py)")
    print("  • Strategy JSON schemas (.json)")
    print("  • Backtest signal files (patterns and signals CSV/JSON)")
    print("  • Backtest results")
    print("  • Chronicle files for strategies")
    print("\n💾 What was preserved:")
    print("  • Learning database (error_learning.db)")
    print("  • Template files")
    print("  • Documentation (README files)")
    print("  • Example strategies")
    print("=" * 60)


if __name__ == '__main__':
    # Ask for confirmation
    print("\n⚠️  This will delete all generated files.")
    print("Learning databases and templates will be preserved.")
    response = input("\nContinue? (yes/no): ").strip().lower()
    
    if response in ['yes', 'y']:
        main()
    else:
        print("❌ Cleanup cancelled.")
