# Generated by Django 5.2.7 on 2025-10-25 11:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('commission', models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Commission rate (e.g., 0.001 = 0.1%)', max_digits=10)),
                ('slippage', models.DecimalField(decimal_places=6, default=Decimal('0.0005'), help_text='Slippage rate', max_digits=10)),
                ('max_position_size', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Maximum position size as fraction of capital', max_digits=5)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss percentage', max_digits=5, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Take profit percentage', max_digits=5, null=True)),
                ('data_source', models.CharField(default='yfinance', max_length=50)),
                ('timeframe', models.CharField(default='1d', max_length=10)),
                ('benchmark_symbol', models.CharField(default='SPY', help_text='Benchmark for comparison', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_template', models.BooleanField(default=False, help_text='Is this a template configuration?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('symbols', models.JSONField(help_text='List of symbols to backtest')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Completion percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=3, help_text='Execution time in seconds', max_digits=10, null=True)),
                ('total_return', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backtest_api.backtestconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategy_api.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_portfolio_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_return_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('annualized_return_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('volatility', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sharpe_ratio', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('calmar_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('max_drawdown_duration', models.IntegerField(help_text='Max drawdown duration in days')),
                ('current_drawdown_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('win_rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_trade_return_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('avg_winning_trade_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('avg_losing_trade_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('largest_winning_trade_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('largest_losing_trade_pct', models.DecimalField(decimal_places=6, max_digits=15)),
                ('profit_factor', models.DecimalField(decimal_places=6, max_digits=15)),
                ('recovery_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('payoff_ratio', models.DecimalField(decimal_places=6, max_digits=15)),
                ('benchmark_return_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('alpha', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('portfolio_values', models.JSONField(help_text='Time series of portfolio values')),
                ('returns', models.JSONField(help_text='Time series of returns')),
                ('drawdowns', models.JSONField(help_text='Time series of drawdowns')),
                ('positions', models.JSONField(help_text='Position sizes over time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backtest_api.backtestrun')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('trade_id', models.CharField(blank=True, max_length=100)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='backtest_api.backtestrun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('entry_date', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('entry_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_commission', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('exit_commission', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('holding_period', models.IntegerField(blank=True, help_text='Holding period in days', null=True)),
                ('signal_name', models.CharField(blank=True, help_text='Signal that triggered the trade', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest_api.backtestrun')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
