# Generated by Django 5.2.6 on 2025-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='strategy_template_id',
            field=models.IntegerField(blank=True, help_text='ID of the StrategyTemplate this session is developing', null=True),
        ),
    ]
