# Generated by Django 5.0.1 on 2026-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_userprofile_account_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='User subscription tier. Free = up to 5 concurrent live bots; Premium = unlimited.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription plan was last changed.', null=True),
        ),
    ]
