# Generated by Django 5.0.1 on 2026-03-11 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy_api', '0009_latestbacktestresult_symbol_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('pid', models.IntegerField(blank=True, help_text='OS process ID of the live trader subprocess', null=True)),
                ('temp_file_path', models.CharField(blank=True, help_text='Path to temp strategy .py file', max_length=500)),
                ('kill_switch_path', models.CharField(blank=True, help_text='Path to kill-switch file for graceful stop', max_length=500)),
                ('symbols', models.JSONField(default=list, help_text='e.g. ["EURUSD", "GBPUSD"]')),
                ('timeframe', models.CharField(default='1h', help_text='e.g. "1h", "1d", "5m"', max_length=10)),
                ('dry_run', models.BooleanField(default=True, help_text='When True, connection is established but NO real orders are sent. Always start with True.')),
                ('risk_pct', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('magic_number', models.IntegerField(default=234567)),
                ('mt5_login', models.IntegerField(help_text='Broker account number')),
                ('mt5_password_encrypted', models.TextField(help_text='Fernet-encrypted broker password')),
                ('mt5_server', models.CharField(help_text='e.g. "FBS-Demo"', max_length=100)),
                ('mt5_terminal_path', models.CharField(blank=True, help_text="Optional: absolute path to terminal64.exe for this user's MT5 installation", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='strategy_api.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
