# Generated by Django 5.0.1 on 2026-03-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_sessions_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human-friendly name e.g. "FBS Demo"', max_length=100
                    ),
                ),
                ("mt5_login", models.IntegerField(help_text="Broker account number")),
                (
                    "mt5_password_encrypted",
                    models.TextField(help_text="Fernet-encrypted broker password"),
                ),
                (
                    "mt5_server",
                    models.CharField(help_text='e.g. "FBS-Demo"', max_length=100),
                ),
                (
                    "mt5_terminal_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional: absolute path to terminal64.exe",
                        max_length=500,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this credential when none is specified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
                "unique_together": {("user", "label")},
            },
        ),
    ]
