# Generated by Django 4.2.29 on 2026-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_sessions_api', '0003_livetradingsession_sl_pips_tp_pips'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradingsession',
            name='data_bars',
            field=models.IntegerField(blank=True, default=5000, help_text='Number of historical bars fetched and used for indicator warm-up (ATR, EMA, RSI, etc.). Higher values reduce NaN signals. Max 5000 (tvDatafeed limit). Defaults to 5000.', null=True),
        ),
    ]
