# Generated by Django 4.2.29 on 2026-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_sessions_api', '0005_livetradingsession_exit_mode_and_risk_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetradingsession',
            name='max_lots',
            field=models.FloatField(blank=True, default=1.0, help_text='Maximum position size in lots per trade. Caps the risk-based position size to prevent over-sizing. Defaults to 1.0 lot.', null=True),
        ),
    ]
