# Generated by Django 5.2.6 on 2025-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_api', '0003_strategychat_strategychatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategychat',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='AI model used', max_length=50),
        ),
    ]
