# Generated by Django 5.2.7 on 2025-10-25 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., trend, momentum, volatility, volume', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Default parameters for the indicator')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading symbol (e.g., AAPL, MSFT)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full company/asset name', max_length=255)),
                ('exchange', models.CharField(blank=True, help_text='Exchange where symbol is traded', max_length=50)),
                ('sector', models.CharField(blank=True, help_text='Business sector', max_length=100)),
                ('industry', models.CharField(blank=True, help_text='Industry classification', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether symbol is actively tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('period', models.CharField(choices=[('1d', '1 Day'), ('5d', '5 Days'), ('1mo', '1 Month'), ('3mo', '3 Months'), ('6mo', '6 Months'), ('1y', '1 Year'), ('2y', '2 Years'), ('5y', '5 Years'), ('10y', '10 Years'), ('ytd', 'Year to Date'), ('max', 'Maximum Available')], default='1y', max_length=10)),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('2m', '2 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('60m', '1 Hour'), ('90m', '90 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('5d', '5 Days'), ('1wk', '1 Week'), ('1mo', '1 Month'), ('3mo', '3 Months')], default='1d', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data_type', models.CharField(help_text='Type of cached data (market_data, indicators, etc.)', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used to generate this cache')),
                ('data', models.JSONField(help_text='Cached data')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('interval', models.CharField(default='1d', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.symbol')),
            ],
            options={
                'ordering': ['symbol', 'timestamp'],
                'unique_together': {('symbol', 'timestamp', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.JSONField(help_text='Indicator value(s) - can be single value or multiple values')),
                ('parameters', models.JSONField(help_text='Parameters used for this calculation')),
                ('interval', models.CharField(default='1d', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.indicator')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.symbol')),
            ],
            options={
                'ordering': ['symbol', 'indicator', 'timestamp'],
                'unique_together': {('symbol', 'indicator', 'timestamp', 'interval')},
            },
        ),
    ]
